apiVersion: v1
kind: Service
metadata:
  annotations:
   beta.cloud.google.com/backend-config: '{"ports": {"9000":"my-backendconfig"}}'
  name: peerjs-server
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: peerjs-server
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local 
status:
  loadBalancer: {}
